import { uniqueNamesGenerator, adjectives } from "unique-names-generator";

const PLACES = [
  "alley",
  "street",
  "station",
  "market",
  "rooftop",
  "tunnel",
  "cafe",
  "studio",
  "lab",
  "library",
  "gallery",
  "hall",
  "garden",
  "forest",
  "shore",
  "harbor",
  "field",
  "cliff",
  "void",
  "archive",
  "channel",
  "lobby",
  "backroom",
  "node",
  "corridor",
  "passage",
  "platform",
  "terminal",
  "basement",
  "attic",
  "warehouse",
  "courtyard",
  "plaza",
  "subway",
  "overpass",
  "underpass",
  "balcony",
  "observatory",
  "controlroom",
  "serverroom",
  "datacenter",
  "edge",
  "threshold",
  "checkpoint",
];

export function generateRandomName() {
  return uniqueNamesGenerator({
    dictionaries: [adjectives, PLACES],
    separator: '-',
    style: "lowerCase",
  }); 
}